---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp

spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - image: ltvnvv/myapp:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          name: myapp

---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  ports:
    - name: myapp-port
      port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: myapp
  type: NodePort
