apiVersion: v1
kind: ConfigMap
metadata:
  name: multitool-config
data:
  HTTP_PORT: "8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-html
data:
  index.html: |
    <html>
    <body>
      <h1>api</h1>
    <body>
    <html>
