apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-multitool
  template:
    metadata:
      labels:
        app: nginx-multitool
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: api-html
              mountPath: /usr/share/nginx/html
            
        - name: multitool
          image: wbitt/network-multitool:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: multitool-config

      volumes:
        - name: api-html
          configMap:
            name: api-html
