apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-multitool-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      containers:
        - name: busybox
          image: busybox:latest
          volumeMounts:
          - name: storage
            mountPath: /shared-data
          command: ["/bin/sh", "-c", "while true; do echo $(date) >> /shared-data/output.log; sleep 5; done"]

        - name: multitool
          image: wbitt/network-multitool:latest
          volumeMounts:
          - name: storage
            mountPath: /shared-data
          ports:
            - containerPort: 8080
          env:
            - name: HTTP_PORT
              value: "8080"

      volumes: 
        - name: storage
          emptyDir: {}
