apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-nodeportservice
spec:
  type: NodePort
  selector:
    app: nginx-multitool
  ports:
    - name: nginx
      protocol: TCP
      nodePort: 30080
      port: 80
    - name: multitool
      protocol: TCP
      nodePort: 30082
      port: 8080
