{
 "title": "Netology",
 "time": { "from": "2024-12-05T11:34:02.278Z", "to": "2024-12-05T11:47:15.020Z" },
 "panels": [
  {
   "title": "Load AVG",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(node_load1{})", "legendFormat": "__auto" },
    { "expr": "avg(node_load5{})", "legendFormat": "__auto" },
    { "expr": "avg(node_load15{})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Free RAM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Утилизация CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg by(instance)(irate(node_cpu_seconds_total{mode=\"idle\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Storage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}