apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application-nginx-{{ .Values.release_version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: {{ .Values.image.name.nginx }}:{{ .Values.image.tag.nginx }}
          ports:
            - containerPort: 80
