apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool:latest
          volumeMounts:
          - name: storage
            mountPath: /shared-data
          ports:
            - containerPort: 8080
          env:
            - name: HTTP_PORT
              value: "8080"

      volumes: 
        - name: storage
          persistentVolumeClaim:
            claimName: pvc-nfs
